### ISSUE TITLE
High Memory Usage Issue Even with pcd_save_en set to False

### ISSUE THREAD

**Issue by HowieHepburn** [fanggenzaiXHBS/fast_lio_balm#2]
**Issue Description:**
I am encountering a significant memory consumption problem while running the project on my system. Even with the `pcd_save_en` parameter set to `false`, the memory usage surges to an excessive level. This occurs despite running the project on my dataset for only a few dozen seconds, consuming up to 30GB of memory.

**System Configuration:**
- Operating System: Ubuntu 20.04
- CPU: Intel i5-12th generation
- Memory: 32GB
- Swap Space: 32GB

**Actual Behavior:**

The memory consumption escalates rapidly, leading to system instability and potential crashes.

**Additional Information:**

I have tried various configurations and settings to mitigate the memory usage issue, but to no avail. Any insights or suggestions on resolving this problem would be greatly appreciated.

Thank you for your attention to this matter.

**Comment by ghost** [comment]
https://github.com/hku-mars/BALM/issues/48
I think this issue will resolve this problem

**Comment by HowieHepburn** [comment]
> [hku-mars/BALM#48](https://github.com/hku-mars/BALM/issues/48) I think this issue will resolve this problem

Thanks a lot, I will try.
